// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240731092019_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp1.Core.Domain.flight", b =>
                {
                    b.Property<int>("flight_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("flight_id"));

                    b.Property<int>("airline_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("route_id")
                        .HasColumnType("int");

                    b.HasKey("flight_id");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("ConsoleApp1.Core.Domain.route", b =>
                {
                    b.Property<int>("route_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("route_id"));

                    b.Property<DateOnly>("departure_date")
                        .HasColumnType("date");

                    b.Property<int>("destination_city_id")
                        .HasColumnType("int");

                    b.Property<int>("origin_city_id")
                        .HasColumnType("int");

                    b.HasKey("route_id");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("ConsoleApp1.Core.Domain.subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("agency_id")
                        .HasColumnType("int");

                    b.Property<int>("destination_city_id")
                        .HasColumnType("int");

                    b.Property<int>("origin_city_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
